In [21]:
class Queue:
    def __init__(self):
        self.queue = []

    def addq(self,v):
        self.queue.append(v)

    def delq(self):
        v = None
        if not self.isempty():
            v = self.queue[0]
            self.queue = self.queue[1:]
        return(v)

    def isempty(self):
        return(self.queue == [])

    def __str__(self):
        return(str(self.queue))

In [22]:
q = Queue()

for i in range(3):
    q.addq(i)
    print(q)
print(q.isempty())

for j in range(3):
    print(q.delq(),q)
print(q.isempty())

[0]
[0, 1]
[0, 1, 2]
False
0 [1, 2]
1 [2]
2 []
True


### Adjacency matrix example

In [23]:
edges = [(0,1),(0,4),(1,2),(2,0),
         (3,4),(3,6),(4,0),(4,3),
#edges = [(0,1),(1,2),(2,0),
#         (3,4),(3,6),(4,3),
         (4,7),(5,3),(5,7),
         (6,5),(7,4),(7,8),
#        (8,9),(9,8)]
         (8,5),(8,9),(9,8)]
uedges = edges + [ (j,i) for (i,j) in edges]

In [24]:
size = 10
import numpy as np
A = np.zeros(shape=(size,size))
for (i,j) in edges:
  A[i,j] = 1
print(A)

[[0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [25]:
def neighbours(AMat,i):
    nbrs = []
    (rows,cols) = AMat.shape
    for j in range(cols):
        if AMat[i,j] == 1:
            nbrs.append(j)
    return(nbrs)

In [26]:
neighbours(A,7)

[4, 8]

### Adjacency list example

In [27]:
size = 10
AL = {}
for i in range(size):
    AL[i] = []
for (i,j) in edges:
    AL[i].append(j)
print(AL)

{0: [1, 4], 1: [2], 2: [0], 3: [4, 6], 4: [0, 3, 7], 5: [3, 7], 6: [5], 7: [4, 8], 8: [5, 9], 9: [8]}


### BFS

In [28]:
def BFS(AMat,v):
    (rows,cols) = AMat.shape
    visited = {}
    for i in range(rows):
        visited[i] = False
    q = Queue()

    visited[v] = True
    q.addq(v)

    while(not q.isempty()):
        j = q.delq()
        for k in neighbours(AMat,j):
            if (not visited[k]):
                visited[k] = True
                q.addq(k)

    return(visited)

In [29]:
BFS(A,0),A

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 array([[0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
        [1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]]))

In [30]:
def BFSList(AList,v):
    visited = {}
    for i in AList.keys():
        visited[i] = False
    q = Queue()

    visited[v] = True
    q.addq(v)

    while(not q.isempty()):
        j = q.delq()
        for k in AList[j]:
            if (not visited[k]):
                visited[k] = True
                q.addq(k)

    return(visited)

In [31]:
BFSList(AL,0)

{0: True,
 1: True,
 2: True,
 3: True,
 4: True,
 5: True,
 6: True,
 7: True,
 8: True,
 9: True}

In [32]:
def BFSListPath(AList,v):
  '''
  this function performs BFS starting from a given vertex v and returns
  two dictionaries: visited, which tells you which vertices are reachable from v,
  and parent, which gives you the shortest path tree with parent information
  to reach each vertex from v.
  '''
  (visited,parent) = ({},{})
  for i in AList.keys():
      visited[i] = False
      parent[i] = -1
  q = Queue()

  visited[v] = True
  q.addq(v)

  while(not q.isempty()):
      j = q.delq()
      for k in AList[j]:
        if (not visited[k]):
          visited[k] = True
          parent[k] = j
          q.addq(k)

  return(visited,parent)


## By following the chain of parent pointers from any vertex back to the starting
## vertex v, we can reconstruct the path from v to that vertex.

In [33]:
BFSListPath(AL,0),AL

(({0: True,
   1: True,
   2: True,
   3: True,
   4: True,
   5: True,
   6: True,
   7: True,
   8: True,
   9: True},
  {0: -1, 1: 0, 2: 1, 3: 4, 4: 0, 5: 6, 6: 3, 7: 4, 8: 7, 9: 8}),
 {0: [1, 4],
  1: [2],
  2: [0],
  3: [4, 6],
  4: [0, 3, 7],
  5: [3, 7],
  6: [5],
  7: [4, 8],
  8: [5, 9],
  9: [8]})

In [34]:
def BFSListPathLevel(AList,v):
    (level,parent) = ({},{})
    for i in AList.keys():
        level[i] = -1
        parent[i] = -1
    q = Queue()

    level[v] = 0
    q.addq(v)

    while(not q.isempty()):
        j = q.delq()
        for k in AList[j]:
            if (level[k] == -1):
                level[k] = level[j]+1
                parent[k] = j
                q.addq(k)

    return(level,parent)

In [35]:
BFSListPathLevel(AL,0)

({0: 0, 1: 1, 2: 2, 3: 2, 4: 1, 5: 4, 6: 3, 7: 2, 8: 3, 9: 4},
 {0: -1, 1: 0, 2: 1, 3: 4, 4: 0, 5: 6, 6: 3, 7: 4, 8: 7, 9: 8})

### DFS

In [36]:
def DFSInit(AMat):
    # Initialization
    (rows,cols) = AMat.shape
    (visited,parent) = ({},{})
    for i in range(rows):
        visited[i] = False
        parent[i] = -1
    return(visited,parent)

def DFS(AMat,visited,parent,v):
    visited[v] = True

    for k in neighbours(AMat,v):
        if (not visited[k]):
            parent[k] = v
            (visited,parent) = DFS(AMat,visited,parent,k)

    return(visited,parent)

In [37]:
(v,p) = DFSInit(A)
DFS(A,v,p,3)

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 {0: 4, 1: 0, 2: 1, 3: -1, 4: 3, 5: 8, 6: 3, 7: 4, 8: 7, 9: 8})

In [38]:
def DFSInitList(AList):
    # Initialization
    (visited,parent) = ({},{})
    for i in AList.keys():
        visited[i] = False
        parent[i] = -1
    return(visited,parent)

def DFSList(AList,visited,parent,v):
    visited[v] = True

    for k in AList[v]:
        if (not visited[k]):
            parent[k] = v
            (visited,parent) = DFSList(AList,visited,parent,k)

    return(visited,parent)

In [39]:
(v,p) = DFSInitList(AL)
DFSList(AL,v,p,3)

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 {0: 4, 1: 0, 2: 1, 3: -1, 4: 3, 5: 8, 6: 3, 7: 4, 8: 7, 9: 8})

In [40]:
(visited,parent) = ({},{})

def DFSInitGlobal(AMat):
    # Initialization
    (rows,cols) = AMat.shape
    for i in range(rows):
        visited[i] = False
        parent[i] = -1
    return

def DFSGlobal(AMat,v):
    visited[v] = True

    for k in neighbours(AMat,v):
        if (not visited[k]):
            parent[k] = v
            DFSGlobal(AMat,k)

    return

In [41]:
DFSInitGlobal(A)
DFSGlobal(A,3)
(visited,parent)

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 {0: 4, 1: 0, 2: 1, 3: -1, 4: 3, 5: 8, 6: 3, 7: 4, 8: 7, 9: 8})

In [42]:
(visited,parent) = ({},{})

def DFSInitListGlobal(AList):
    # Initialization
    for i in AList.keys():
        visited[i] = False
        parent[i] = -1
    return

def DFSListGlobal(AList,v):
    visited[v] = True

    for k in AList[v]:
        if (not visited[k]):
            parent[k] = v
            DFSListGlobal(AList,k)

    return

In [43]:
DFSInitListGlobal(AL)
DFSListGlobal(AL,3)
(visited,parent)

({0: True,
  1: True,
  2: True,
  3: True,
  4: True,
  5: True,
  6: True,
  7: True,
  8: True,
  9: True},
 {0: 4, 1: 0, 2: 1, 3: -1, 4: 3, 5: 8, 6: 3, 7: 4, 8: 7, 9: 8})

In [44]:
def Components(AList):
    component = {}
    for i in AList.keys():
        component[i] = -1

    (compid,seen) = (0,0)

    while seen < max(AList.keys()):
        startv = min([i for i in AList.keys()
                      if component[i] == -1])
        visited = BFSList(AList,startv)
        for i in visited.keys():
            if visited[i]:
                seen = seen + 1
                component[i] = compid
        compid = compid + 1

    return(component)

In [45]:
Components(AL)

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}

In [46]:
(visited,pre,post) = ({},{},{})

def DFSInitPrePost(AList):
    # Initialization
    for i in AList.keys():
        visited[i] = False
        (pre[i],post[i]) = (-1,-1)
    return

def DFSListPrePost(AList,v,count):
    visited[v] = True
    pre[v] = count
    count = count+1

    for k in AList[v]:
        if (not visited[k]):
            count = DFSListPrePost(AList,k,count)
    post[v] = count
    count = count+1

    return(count)

In [47]:
DFSInitPrePost(AL)
DFSListPrePost(AL,0,0)
AL,(visited,pre,post)

({0: [1, 4],
  1: [2],
  2: [0],
  3: [4, 6],
  4: [0, 3, 7],
  5: [3, 7],
  6: [5],
  7: [4, 8],
  8: [5, 9],
  9: [8]},
 ({0: True,
   1: True,
   2: True,
   3: True,
   4: True,
   5: True,
   6: True,
   7: True,
   8: True,
   9: True},
  {0: 0, 1: 1, 2: 2, 3: 6, 4: 5, 5: 8, 6: 7, 7: 9, 8: 10, 9: 11},
  {0: 19, 1: 4, 2: 3, 3: 17, 4: 18, 5: 15, 6: 16, 7: 14, 8: 13, 9: 12}))

In [48]:
edges=[(0,1),(1,0),(0,4),(4,0),(4,8),(8,4),(8,9),(9,8),(4,9),(9,4)]

In [49]:
def toposort(AMat):
    (rows,cols) = AMat.shape
    indegree = {}
    toposortlist = []

    for c in range(cols):
        indegree[c] = 0
        for r in range(rows):
            if AMat[r,c] == 1:
                indegree[c] = indegree[c] + 1

    for i in range(rows):
        j = min([k for k in range(cols)
                 if indegree[k] == 0])
        toposortlist.append(j)
        indegree[j] = indegree[j]-1
        for k in range(cols):
            if AMat[j,k] == 1:
                indegree[k] = indegree[k] - 1

    return(toposortlist)

In [50]:
def toposortlist(AList):
    (indegree,toposortlist) = ({},[])
    zerodegreeq = Queue()

    for u in AList.keys():
        indegree[u] = 0

    for u in AList.keys():
        for v in AList[u]:
            indegree[v] = indegree[v] + 1

    for u in AList.keys():
        if indegree[u] == 0:
            zerodegreeq.addq(u)

    while (not zerodegreeq.isempty()):
        j = zerodegreeq.delq()
        toposortlist.append(j)
        indegree[j] = indegree[j]-1
        for k in AList[j]:
            indegree[k] = indegree[k] - 1
            if indegree[k] == 0:
                zerodegreeq.addq(k)

    return(toposortlist)

In [51]:
edges=[(0,2),(0,3),(0,4),(1,2),(1,7),(2,5),(3,5),(3,7),(4,7),(5,6),(6,7)]

In [55]:
toposortlist(AL)

[]

In [56]:
toposortlist(AL)

[]

In [57]:
def longestpathlist(AList):
    (indegree,lpath) = ({},{})
    zerodegreeq = Queue()

    for u in AList.keys():
        (indegree[u],lpath[u]) = (0,0)

    for u in AList.keys():
        for v in AList[u]:
            indegree[v] = indegree[v] + 1

    for u in AList.keys():
        if indegree[u] == 0:
            zerodegreeq.addq(u)

    while (not zerodegreeq.isempty()):
        j = zerodegreeq.delq()
        indegree[j] = indegree[j]-1
        for k in AList[j]:
            indegree[k] = indegree[k] - 1
            lpath[k] = max(lpath[k],lpath[j]+1)
            if indegree[k] == 0:
                zerodegreeq.addq(k)

    return(lpath)

In [58]:
longestpathlist(AL)

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}